//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pcejin.rc
//
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDD_MEM_VIEW                    106
#define IDR_MAINFRAME                   128
#define IDC_CV                          129
#define IDI_ICON1                       130
#define IDB_BITMAP1                     135
#define IDC_WATCHLIST                   200
#define IDC_PROMPT_EDIT                 201
#define IDD_PROMPT                      202
#define RAMMENU_FILE_RECENT             203
#define IDC_EDIT_COMPAREADDRESS         204
#define IDC_1_BYTE                      205
#define IDC_2_BYTES                     206
#define IDC_4_BYTES                     207
#define IDC_SIGNED                      208
#define IDC_UNSIGNED                    209
#define IDC_HEX                         210
#define ID_WATCHES_UPDOWN               211
#define IDC_C_WATCH_UP                  212
#define IDC_C_WATCH_DOWN                213
#define RAMMENU_FILE_SAVE               214
#define RAMMENU_FILE_SAVEAS             215
#define RAMMENU_FILE_OPEN               216
#define RAMMENU_FILE_APPEND             217
#define RAMMENU_FILE_AUTOLOAD           218
#define RAMMENU_FILE_SAVEWINDOW         219
#define RAMMENU_FILE_NEW                220
#define IDC_C_WATCH_REMOVE              221
#define IDC_C_WATCH_EDIT                222
#define IDD_EDITWATCH                   223
#define IDC_C_WATCH_DUPLICATE           224
#define IDC_C_ADDCHEAT                  225
#define IDC_C_WATCH                     226
#define ID_RAM_WATCH                    227
#define IDC_C_WATCH_DUPLICATE2          227
#define IDC_C_WATCH_SEPARATE            227
#define IDD_RAMWATCH                    228
#define IDM_RESET                       229
#define IDC_EDIT_COMPAREVALUE           230
#define IDC_EDIT_COMPARECHANGES         231
#define IDC_EDIT_DIFFBY                 232
#define IDC_EDIT_MODBY                  233
#define IDC_RAMLIST                     234
#define IDC_C_ELIMINATE                 235
#define IDC_C_MISALIGN                  236
#define IDC_C_AUTOSEARCH                237
#define IDC_MISALIGN                    238
#define IDC_LESSTHAN                    239
#define IDC_MORETHAN                    240
#define IDC_NOMORETHAN                  241
#define IDC_NOLESSTHAN                  242
#define IDC_EQUALTO                     243
#define IDC_DIFFERENTFROM               244
#define IDC_MODULO                      245
#define IDC_PREVIOUSVALUE               246
#define IDC_SPECIFICVALUE               247
#define IDC_SPECIFICADDRESS             248
#define IDC_NUMBEROFCHANGES             249
#define IDC_DIFFERENTBY                 250
#define IDC_C_RESET                     251
#define IDC_C_RESET_CHANGES             252
#define IDC_C_UNDO                      253
#define IDC_C_SEARCH                    254
#define ID_RAM_SEARCH                   255
#define IDD_RAMSEARCH                   256
#define IDC_PROMPT_TEXT                 257
#define IDM_RECORD_MOVIE                259
#define IDM_PLAY_MOVIE                  260
#define IDM_STOPMOVIE                   261
#define IDM_FILE_RECORDAVI              262
#define IDM_FILE_STOPAVI                263
#define IDM_OPEN_ROM                    264
#define IDM_FILE_RECORDWAV              265
#define IDM_FILE_STOPWAV                266
#define ID_VIEW_DISP_BOTH               267
#define ID_VIEW_DISP_LEFT               268
#define ID_VIEW_DISP_RIGHT              269
#define ID_VIEW_DISP_DISABLE            270
#define ID_SPLIT_MODE_ANAGLYPH          271
#define ID_SPLIT_MODE_CSCOPE            272
#define ID_SPLIT_MODE_SIDEBYSIDE        273
#define ID_SPLIT_MODE_PBARRIER          274
#define ID_COLOR_MODE_REDBLUE           275
#define ID_COLOR_MODE_GREYSCALE         276
#define ID_PIXEL_SEP_16                 277
#define ID_PIXEL_SEP_32                 278
#define ID_PIXEL_SEP_48                 279
#define ID_PIXEL_SEP_64                 280
#define ID_PIXEL_SEP_80                 281
#define ID_PIXEL_SEP_96                 282
#define ID_COLOR_MODE_REDCYAN           283
#define ID_COLOR_MODE_REDELECTRICCYAN   284
#define ID_COLOR_MODE_REDGREEN          285
#define ID_COLOR_MODE_GREENMAGENTA      286
#define ID_COLOR_MODE_YELLOWBLUE        287
#define ID_VIEW_OPENCONSOLE             288
#define IDC_UP                          400
#define IDC_LEFT                        401
#define IDC_DOWN                        402
#define IDC_RIGHT                       403
#define IDC_I                           404
#define IDC_II                          405
#define IDC_RUN                         406
#define IDC_SELECT                      407
#define IDC_LABEL_RIGHT                 410
#define IDC_LABEL_UP                    411
#define IDC_LABEL_LEFT                  412
#define IDC_LABEL_DOWN                  413
#define IDC_LABEL_I                     414
#define IDC_LABEL_II                    415
#define IDC_LABEL_SELECT                416
#define IDC_LABEL_RUN                   417
#define IDD_INPUTCONFIG                 418
#define IDC_ALLOWLEFTRIGHT              419
#define IDM_INPUT_CONFIG                420
#define IDC_Y                           421
#define IDC_X                           422
#define IDC_L                           423
#define IDC_R                           424
#define IDC_UPLEFT                      425
#define IDC_UPRIGHT                     426
#define IDC_DWNRIGHT                    427
#define IDC_DWNLEFT                     428
#define IDC_LABEL_X                     439
#define IDC_LABEL_Y                     440
#define IDC_LABEL_L                     441
#define IDC_LABEL_R                     442
#define IDC_LABEL_UPLEFT                443
#define IDC_LABEL_DOWNRIGHT             445
#define IDC_LABEL_UPRIGHT               446
#define IDC_LABEL_DOWNLEFT              447
#define IDC_LID                         448
#define IDC_LABEL_X2                    449
#define IDC_LABEL_X3                    450
#define IDC_DEBUG                       451
#define IDC_BIOSTEXT                    452
#define IDC_BIOSBROWSE                  453
#define IDM_BIOS_CONFIG                 454
#define IDD_BIOS                        455
#define IDC_Right_UP                    456
#define IDC_Right_LEFT                  457
#define IDC_Right_DOWN                  458
#define IDC_Right_RIGHT                 459
#define IDC_WINDOW1X                    500
#define IDC_WINDOW2X                    501
#define IDC_WINDOW3X                    502
#define IDC_WINDOW4X                    503
#define IDC_ASPECT                      504
#define ID_VIEW_FRAMECOUNTER            505
#define ID_VIEW_DISPLAYINPUT            506
#define ID_VIEW_DISPLAYLAG              507
#define ID_VIEW_DISPLAYSTATESLOTS       508
#define IDC_JPCOMBO                     509
#define IDC_JPTOGGLE                    510
#define IDM_MUTE                        511
#define ID_VIEW_MIXLEFTRIGHT            512
#define IDC_WINDOW15X                   513
#define IDC_WINDOW25X                   514
#define IDC_MLENGTH                     600
#define IDC_MFRAMES                     601
#define PM_FILENAME                     602
#define IDC_MRERECORDCOUNT              603
#define IDC_MROM                        604
#define IDC_CHECK_READONLY              605
#define ID_BROWSE                       606
#define IDC_START_FROM_SRAM             607
#define IDC_EDIT_AUTHOR                 608
#define IDC_EDIT_FILENAME               609
#define IDC_BUTTON_BROWSEFILE           610
#define IDC_BUTTON_BROWSESRAM           611
#define IDC_EDIT_SRAMFILENAME           612
#define IDD_RECORDMOVIE                 613
#define IDC_2_PLAYER                    614
#define IDC_TXT_VERSION                 615
#define IDC_LUACONSOLE                  700
#define IDC_EDIT_LUAPATH                701
#define IDC_BUTTON_LUARUN               702
#define IDC_BUTTON_LUASTOP              703
#define IDC_BUTTON_LUABROWSE            704
#define IDC_BUTTON_LUAEDIT              705
#define IDC_NOTIFY_SUBSERVIENT          706
#define IDD_LUA                         707
#define IDC_NEW_LUA_SCRIPT              708
#define IDM_CONVERT_MCM                 709
#define ID_FILE_RECENTROM               710
#define ID_CANCEL                       1002
#define IDC_COMBO1                      1003
#define IDC_GO                          1004
#define IDC_TEXTDUMP                    1005
#define IDC_MEMVIEWBOX                  1006
#define IDC_ADDRESS                     1007
#define IDC_RAWDUMP                     1008
#define IDC_REGION                      1009
#define IDC_VIEWMODE                    1010
#define IDC_DUMPALL                     1011
#define IDM_MEMORY                      32770
#define ID_COLORING_RED                 32771
#define ID_COLOR_MODE_RED               32772
#define ID_SPLITTINGMODE_OCULUSRIFT     32773
#define ID_SPLIT_MODE_OVR               32774
#define ID_VIEW_OCULUSRIFTMODE          32775
#define ID_OCULUSRIFTMODE_HEADLOCKED    32776
#define ID_OCULUSRIFTMODE_IMMERSIVE     32777
#define IDC_LABEL_HK1                   60001
#define IDC_LABEL_HK2                   60002
#define IDC_LABEL_HK3                   60003
#define IDC_LABEL_HK4                   60004
#define IDC_LABEL_HK5                   60005
#define IDC_LABEL_HK6                   60006
#define IDC_LABEL_HK7                   60007
#define IDC_LABEL_HK8                   60008
#define IDC_LABEL_HK9                   60009
#define IDC_HOTKEY1                     60011
#define IDC_HOTKEY2                     60012
#define IDC_HOTKEY3                     60013
#define IDC_HOTKEY4                     60014
#define IDC_HOTKEY5                     60015
#define IDC_HOTKEY6                     60016
#define IDC_HOTKEY7                     60017
#define IDC_HOTKEY8                     60018
#define IDC_HOTKEY9                     60019
#define IDC_HOTKEY10                    60020
#define IDC_HOTKEY11                    60021
#define IDC_HOTKEY12                    60022
#define IDC_HOTKEY13                    60023
#define IDC_HOTKEY14                    60024
#define IDC_HOTKEY15                    60025
#define IDC_HOTKEY16                    60026
#define IDC_HOTKEY17                    60027
#define IDC_HOTKEY18                    60028
#define IDC_HOTKEY19                    60029
#define IDC_HOTKEY20                    60030
#define IDC_LABEL_HK10                  60031
#define IDC_LABEL_HK11                  60032
#define IDC_LABEL_HK12                  60033
#define IDC_LABEL_HK13                  60034
#define IDC_LABEL_HK14                  60035
#define IDC_LABEL_HK15                  60036
#define IDC_LABEL_HK16                  60037
#define IDC_LABEL_HK17                  60038
#define IDC_LABEL_HK19                  60040
#define IDC_LABEL_HK20                  60041
#define IDC_LABEL_HK18                  60049
#define IDC_HKCOMBO                     60077
#define IDD_KEYCUSTOM                   60078
#define IDM_HOTKEY_CONFIG               60079
#define IDC_LABEL_BLUE                  60080
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
